<?php
function cookie_poll_menu(){
    $items['cookie_poll'] = array(
        'title' => "Whats your flavorite cookie dough? (Must be in Oregon to participate)",
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cookie_poll_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cookie_poll_results_page'] = array(
        'title' => 'Ye results are in',
        'page callback' => 'cookie_poll_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}
function cookie_poll_form(){
    $form['cookie_flavor'] = array(
        '#title' => 'Cookie Dough Flavor',
        '#type' => 'textfield',
        '#description' => 'Whats your flavorite?',
        '#required' => TRUE,
    );
    $form['state'] = array(
        '#title' => 'State',
        '#type' => 'textfield',
        '#description' => 'Open only to Oregon residents',
        '#required' => TRUE,
        '#element_validate' => array('element_validate_state'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'submit',
    );
    return $form;
}
function element_validate_state($element){
    $state_abbreviations = array("AK","AL","AR","AZ","CA","CO","CT","DC","DE","FL","GA","GU","HI","IA","ID","IL","IN","KS","KY","LA","MA","MD","ME","MH","MI","MN","MO","MS","MT","NC","ND","NE","NH","NJ","NM","NV","NY", "OH","OK","OR","PA","PR","PW","RI","SC","SD","TN","TX","UT","VA","VI","VT","WA","WI","WV","WY");
    $state_names = array("Alabama", "Alaska", "American Samoa", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "District Of Columbia", "Federated States Of Micronesia", "Florida", "Georgia", "Guam", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Marshall Islands", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Northern Mariana Islands", "Ohio", "Oklahoma", "Oregon", "Palau", "Pennsylvania", "Puerto Rico", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virgin Islands", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming");
    $state = $element['#value'];
    if(strlen($state) == 2){
        $state = strtoupper($state);
        if(!in_array($state, $state_abbreviations)){
            form_error($element, t('that isn\'t a state abbreviation'));
        }
    }
    else{
        $state = strtolower($state);
        $state = ucfirst($state);
        if(!in_array($state, $state_names)){
            form_error($element, t('that wasn\'t in our array of state and territory names'));
        }
    }
}

function cookie_poll_form_submit($form, &$form_state){
    $_SESSION['result'] = '
    <p>Studies show that many people in '.$form_state['values']['state'].' like '.$form_state['values']['cookie_flavor'].' as well! Congrats. You are basic.</p>
    ';
    $form_state['redirect'] = 'cookie_poll_results_page';
}
function cookie_poll_results(){
    return $_SESSION['result'];
}
